name: Build image
on:
  push:
    branches:
    - master
jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Prepare destination directory
      run: |
        mkdir -p dist/tmp
        chmod uga+rwx dist/tmp

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build -v -ldflags="-s -w" -o dist/vogon-go .

    - name: Create image
      run: podman build --tag ghcr.io/zlogic/vogon-go:${{ github.ref_name }}-${{ matrix.arch }} --arch=${{ matrix.arch }} --file .github/Dockerfile dist

    - name: Save image file
      run: podman save ghcr.io/zlogic/vogon-go:${{ github.ref_name }}-${{ matrix.arch }} > vogon-go.tar

    - name: Upload image artifact
      uses: actions/upload-artifact@v2
      with:
        name: vogon-go-${{ matrix.arch }}
        path: vogon-go.tar
        retention-days: 1

  push-images:
    name: Combine and push images
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Download image artifacts
      id: download
      uses: actions/download-artifact@v2

    - name: Create manifest
      run: podman manifest create vogon-go:${{ github.ref_name }}

    - name: Import images into Podman
      run: |
        for img in ${{ steps.download.outputs.download-path }}/*/vogon-go.tar; do
          podman load < ${img}
          podman manifest add vogon-go:${{ github.ref_name }} docker-archive:${img}
        done

    - name: Login into container registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push manifest
      run: podman manifest push --all vogon-go:${{ github.ref_name }} docker://ghcr.io/zlogic/vogon-go:${{ github.ref_name }}

    - name: Push images
      run: |
        podman images --noheading --format="{{.Repository}}:{{.Tag}}" --filter "reference=ghcr.io/zlogic/vogon-go:${{ github.ref_name }}-*" | \
        xargs -I '{}' podman push '{}'
